// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARwozW5ds6WWdBDELdqXmOtv6iwJH05nI',
    appId: '1:560775100270:web:c10b8d78ebdb49adb2337f',
    messagingSenderId: '560775100270',
    projectId: 'authentication-in-flutte-561bc',
    authDomain: 'authentication-in-flutte-561bc.firebaseapp.com',
    storageBucket: 'authentication-in-flutte-561bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLbaKpjMa6UGVCzSUo4BkFys8VBbqPQ8',
    appId: '1:560775100270:android:3e49d46a62ddb637b2337f',
    messagingSenderId: '560775100270',
    projectId: 'authentication-in-flutte-561bc',
    storageBucket: 'authentication-in-flutte-561bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOX3eMd9QEo1qepzjSLW6_xM_CRFcb5Oc',
    appId: '1:560775100270:ios:e410ca716e3fb8b2b2337f',
    messagingSenderId: '560775100270',
    projectId: 'authentication-in-flutte-561bc',
    storageBucket: 'authentication-in-flutte-561bc.appspot.com',
    iosBundleId: 'com.example.authenticationInFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOX3eMd9QEo1qepzjSLW6_xM_CRFcb5Oc',
    appId: '1:560775100270:ios:e410ca716e3fb8b2b2337f',
    messagingSenderId: '560775100270',
    projectId: 'authentication-in-flutte-561bc',
    storageBucket: 'authentication-in-flutte-561bc.appspot.com',
    iosBundleId: 'com.example.authenticationInFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARwozW5ds6WWdBDELdqXmOtv6iwJH05nI',
    appId: '1:560775100270:web:17cd3b489bf3667ab2337f',
    messagingSenderId: '560775100270',
    projectId: 'authentication-in-flutte-561bc',
    authDomain: 'authentication-in-flutte-561bc.firebaseapp.com',
    storageBucket: 'authentication-in-flutte-561bc.appspot.com',
  );
}
